export const PAGE_LOADED = 'PAGE_LOADED'

export const ROOM_MODULE_LOADED = 'ROOM_MODULE_LOADED'
export const ROOM_UPDATE_TITLE = 'ROOM_UPDATE_TITLE'

export const CATEGORY_INIT = 'CATEGORY_INIT'
export const CATEGORY_ADD = 'CATEGORY_ADD'
export const CATEGORY_UPDATE = 'CATEGORY_UPDATE'
export const CATEGORY_DELETE = 'CATEGORY_DELETE'
